<?php
/**
 * Crypt
 *
 * @author Ashley Kitson
 * @copyright Ashley Kitson, 2015, UK
 * @license GPL V3+ See LICENSE.md
 */
namespace Chippyash\Test\Crypt\Method\HexUtil;

use Chippyash\Crypt\Method\HexUtil\HexUtil;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-10-02 at 15:06:41.
 */
class HexUtilTest extends \PHPUnit_Framework_TestCase {

    public function testYouCanConvertBinaryValueToABinaryString() {
        $hex = 'F';
        $binary = HexUtil::hex2bin($hex);
        $this->assertEquals('1111', HexUtil::bin2char($binary));
    }
}
